name: master workflow

on:
  push:
    branches: [ test/ci ]

jobs:
  build_and_push_to_publicecr:
    runs-on: ubuntu-latest
    name: build_and_push_to_publicecr
    outputs:
      directory: ${{ steps.set-directory.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get results
        id: set-directory
        run: |
          results=($(ls | grep -E "[0-9]{1,2}_[0-9]{1,2}_[0-9]{1,2}"))
          echo "::set-output name=value::${results[@]}"

  get_directory:
    needs: build_and_push_to_publicecr
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     directory: ${{fromJson(needs.set-matrix.outputs.something)}}

    steps:
      - run: echo ${{ needs.build_and_push_to_publicecr.outputs.directory }}
        

      # - name: 2
      #   run: |
      #     for v in ${results[@]}; do
      #       version=$(echo ${v} | sed -e s/_/./g)
      #       echo $version
      #     done
