name: master workflow

on:
  push:
    branches: [ test/ci ]

jobs:
  build_and_push_to_publicecr:
    runs-on: ubuntu-latest
    name: build_and_push_to_publicecr
    outputs:
      directory: ${{ steps.set-directory.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get results
        id: set-directory
        run: |
          results="[\"$(ls | grep -E "[0-9]{1,2}_[0-9]{1,2}_[0-9]{1,2}"  | tr '\n' ',' | sed -e 's/,$/\n/g' | sed -e 's/,/\",\"/g')\"]"
          list=$(echo $results | jq -c)
          echo "::set-output name=value::${list}"

  get_directory:
    needs: build_and_push_to_publicecr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{fromJson(needs.build_and_push_to_publicecr.outputs.directory)}}
    steps:
      # - run: |
      #     echo ${{ matrix.directory }}
      - run: |
          # results=${{ needs.build_and_push_to_publicecr.outputs.directory }}
          echo ${{ needs.build_and_push_to_publicecr.outputs.directory }}
      #     echo results
      #     # for v in ${results[@]}; do
      #     #   version=$(echo ${v} | sed -e s/_/./g)
      #     #   echo $version
      #     # done
